FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40
RUN apk add --no-cache openvpn iptables iproute2 python3 curl bind-tools
COPY scripts/vpn.py /opt/gateway/vpn.py
RUN chmod 0555 /opt/gateway/vpn.py
ENTRYPOINT ["python3", "-u", "/opt/gateway/vpn.py"]
