logoutput: stderr
internal.protocol: ipv4
internal: 127.0.0.1 port = 11080
external.protocol: ipv4
external: tun0
external.rotation: none
user.privileged: proxyuser
user.unprivileged: proxyuser
clientmethod: none
socksmethod: none
timeout.connect: 12
timeout.negotiate: 15
client pass {
    from: 127.0.0.1/32 to: 0.0.0.0/0
}
socks block {
    from: 127.0.0.1/32 to: 127.0.0.0/8
}
socks block {
    from: 127.0.0.1/32 to: 169.254.0.0/16
}
socks pass {
    from: 127.0.0.1/32 to: 0.0.0.0/0
    command: connect
    protocol: tcp
    socksmethod: none
}
